[[headers]]
     # Define which paths this specific [[headers]] block will cover.
      for = "/*"
        [headers.values]
        Access-Control-Allow-Origin = "https://mern-stack-project-musiko-music-app.vercel.app"